---
# This file is managed via modulesync and should not be edited manually.
# See https://github.com/voxpupuli/modulesync_config for details.

.github/workflows/ci.yml:
  override: true
.github/workflows/release.yml:
  override: true

Gemfile:
  required:
    ':development':
      - gem: 'voxpupuli-test'
        version: '~> 7.0'
      - gem: 'voxpupuli-acceptance'
        version: '~> 2.0'

Rakefile:
  override: false

spec/spec_helper.rb:
  override: false
